### ISSUE TITLE
Remove sections from generic and customized worksheets for which number of questions is set as 0

### ISSUE THREAD

**Issue by ishanisri** [PaiAkshay998/WorkGen#31]

**Comment by ishanisri** [comment]
Currently, if a user clicks on worksheet type "test paper" on the homepage, the new page asks the user to select the worksheet type again. This happens with all the three worksheet types. We can get rid of this extra step.

**Comment by Jayashrri** [comment]
@ishanisri Isn't this description for Issue #36 instead? Should I work on both of them?

**Comment by ishanisri** [comment]
Yeah sure, I made this a separate issue only yesterday. In this one, we want to remove sections for which we have 0 questions in the question paper.

**Comment by ishanisri** [comment]
Updated  #36 with its description. This and #36 are two separate issues.
