### ISSUE TITLE
Customized paper generation when not logged in gives error 500

### ISSUE THREAD

**Issue by sandy9999** [PaiAkshay998/WorkGen#34]

**Comment by KIRA009** [comment]
How do I replicate this issue?

**Comment by ishanisri** [comment]
Logout from a mentor and then try generating a customised paper

**Comment by KIRA009** [comment]
For generating customised paper, you need to make a post request on the `get_customize_paper` url. However, I don't see any method (like a button or a form) to make any such request, both when logged in and logged out.

**Comment by ishanisri** [comment]
Did you check the js file for the webpage?

**Comment by KIRA009** [comment]
Ok found it. What is be the desired response? Redirect to login page?
